### ISSUE TITLE
Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by ghost** [sinsongdev/gradle-cash-to-maven-repo#2]
Hi, sir.
I am using this python file for android repository.
But it has issue as following.

```
PS D:\repo\android> py .\gradle_cache_to_repo.py
Traceback (most recent call last):
  File "D:\repo\android\gradle_cache_to_repo.py", line 66, in <module>
    processGroup(group)
  File "D:\repo\android\gradle_cache_to_repo.py", line 25, in processGroup
    os.makedirs(dst + group_dir)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:/repo/android/lib/com/github/chrisbanes/photoview'
```

Please fix it.

**Comment by sinsongdev** [comment]
Hi, there.
Just fixed the issue.
