### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghost** [sinsongdev/gradle-cash-to-maven-repo#3]
I run it on Windows10.
` python .\gradle_cache_to_repo.py`

But it failed as below. Please fix it.
`
Traceback (most recent call last):
  File ".\gradle_cache_to_repo.py", line 71, in <module>
    processGroup(group)
  File ".\gradle_cache_to_repo.py", line 34, in processGroup
    processArtifect(group, group_dir, artifect)
  File ".\gradle_cache_to_repo.py", line 48, in processArtifect
    processVersion(group, artifect, artifect_dir, version)
  File ".\gradle_cache_to_repo.py", line 66, in processVersion
    copyfile(src_file_path, dst_file_path)
  File "C:\Python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:/Users/mario/.gradle/caches/modules-2/files-2.1/com.android.tools.utp/android-test-plugin-host-additional-test-output-proto/30.2.0-alpha04/3a5204e32a230432c8142ebcb624b02615f7533f/android-test-plugin-host-additional-test-output-proto-30.2.0-alpha04-sources.jar'
`

**Comment by sinsongdev** [comment]
Fixed this issue.
(commit d01762016001c259a1196011404f975c80f7e1c4)
